### ISSUE TITLE
older ospd version 

### ISSUE THREAD

**Issue by Doratmon** [greenbone/ospd#315]
If I use older version ospd like v1.0.0, does python3 environment is also required? (‘coz our team may use openvas 8, Thanks)

**Comment by cfi-gb** [comment]
Please use https://community.greenbone.net/c/osp/13 for such kind of questions / support requests. Thanks for your understanding.

**Comment by bjoernricks** [comment]
You should **NOT** use such an old version of OpenVAS. It is heavily heavily outdated. Please take a look at https://community.greenbone.net/t/about-the-greenbone-source-edition-gse-category/176 for current version information.
