### ISSUE TITLE
[20.8.1] tests are installed

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/ospd#330]
After call setup.py install, the following files will installed:
 /usr/lib/python3.6/site-packages/tests/command/__init__.py
   /usr/lib/python3.6/site-packages/tests/command/__pycache__/__init__.cpython-36.opt-1.pyc
   /usr/lib/python3.6/site-packages/tests/command/__pycache__/__init__.cpython-36.pyc
   /usr/lib/python3.6/site-packages/tests/command/__pycache__/test_command.cpython-36.opt-1.pyc
   /usr/lib/python3.6/site-packages/tests/command/__pycache__/test_command.cpython-36.pyc
   /usr/lib/python3.6/site-packages/tests/command/__pycache__/test_commands.cpython-36.opt-1.pyc
   /usr/lib/python3.6/site-packages/tests/command/__pycache__/test_commands.cpython-36.pyc
   /usr/lib/python3.6/site-packages/tests/command/__pycache__/test_registry.cpython-36.opt-1.pyc
   /usr/lib/python3.6/site-packages/tests/command/__pycache__/test_registry.cpython-36.pyc
   /usr/lib/python3.6/site-packages/tests/command/test_command.py
   /usr/lib/python3.6/site-packages/tests/command/test_commands.py
   /usr/lib/python3.6/site-packages/tests/command/test_registry.py

I think, the test files should not be installed on the target.

**Comment by bjoernricks** [comment]
Already fixed in master with #317. Will come with next release. Just as a side note, we don't use `setup.py` to build the distributables. We are using `poetry build` which doesn't include the test directory.
