### ISSUE TITLE
Write your own OSPD wrapper link in README is broken

### ISSUE THREAD

**Issue by DamionGans** [greenbone/ospd#343]
I wanted to learn how to create an OSPD wrapper myself, but the link on how to create one in the README is broken. Can you please fix the link? Thanks!

**Comment by DamionGans** [comment]
This is the link: https://docs.greenbone.net/GSM-Manual/gos-3.1/en/osp.html#how-to-write-your-own-osp-wrapper

**Comment by jjnicola** [comment]
Hi @DamionGans,

maybe you want to take a look at our [ospd-example-scanner](https://github.com/greenbone/ospd-example-scanner). You can use it as template, and it is self documented.
For other questions, you can better visit our community portal https://community.greenbone.net/c/osp/
Best regards
