### ISSUE TITLE
ospd 21.4.3 has requirement psutil<6.0.0,>=5.7.2, but you'll have psutil 5.5.1 which is incompatible.

### ISSUE THREAD

**Issue by Dexus** [greenbone/ospd#452]
Please when you say you build will work on buster then I expect your setup works without running own PIP installs.

https://greenbone.github.io/docs/gvm-21.04/index.html is outdated then and on some points wrong.

To fix this:
```shell
echo 'deb http://deb.debian.org/debian buster-backports main' >/etc/apt/sources.list.d/backports.list
apt-get update
apt-get install python3-psutil/buster-backports
```

**Comment by jjnicola** [comment]
Fixed
